name: Prerelease

on:
  pull_request:

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.7.0

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          # This doesn't just set the registry url, but also sets
          # the right configuration in .npmrc that reads NPM token
          # from NPM_AUTH_TOKEN environment variable.
          # It actually creates a .npmrc in a temporary folder
          # and sets the NPM_CONFIG_USERCONFIG environment variable.
          registry-url: https://registry.npmjs.org
          cache: 'pnpm'

      - name: Install dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: Build
        shell: bash
        run: pnpm --filter qwik build

      - run: pnpm dlx pkg-pr-new publish --pnpm ./packages/qwik
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN is provided automatically in any repository
